import { defineStore } from "pinia";

export interface Project {
  id: number;
  title: string;
  images: string[];
  serviceId: number;
}

export const usePortfolio = defineStore("projects", {
  state: () => ({
    projects: <Project[]>[
      {
        id: 12,
        serviceId: 10,
        title: "10-26 Holmesway Pl, Acton",
        images: [
          "/images/portfolio/10-26 Holmesway Pl, Acton/1.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/2.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/3.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/4.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/5.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/6.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/7.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/8.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/9.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/10.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/11.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/12.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/13.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/14.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/15.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/16.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/17.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/18.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/19.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/20.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/21.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/22.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/23.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/24.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/25.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/26.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/27.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/28.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/29.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/30.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/31.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/32.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/33.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/34.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/35.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/36.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/37.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/38.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/39.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/40.jpg",
        ],
      },
      {
        id: 12,
        serviceId: 10,
        title: "134-700 Osgoode Dr",
        images: [
          "/images/portfolio/134-700 Osgoode Dr/1.jpg",
          "/images/portfolio/134-700 Osgoode Dr/2.jpg",
          "/images/portfolio/134-700 Osgoode Dr/3.jpg",
          "/images/portfolio/134-700 Osgoode Dr/4.jpg",
          "/images/portfolio/134-700 Osgoode Dr/5.jpg",
          "/images/portfolio/134-700 Osgoode Dr/6.jpg",
          "/images/portfolio/134-700 Osgoode Dr/7.jpg",
          "/images/portfolio/134-700 Osgoode Dr/8.jpg",
          "/images/portfolio/134-700 Osgoode Dr/9.jpg",
          "/images/portfolio/134-700 Osgoode Dr/10.jpg",
          "/images/portfolio/134-700 Osgoode Dr/11.jpg",
          "/images/portfolio/134-700 Osgoode Dr/12.jpg",
          "/images/portfolio/134-700 Osgoode Dr/13.jpg",
          "/images/portfolio/134-700 Osgoode Dr/14.jpg",
          "/images/portfolio/134-700 Osgoode Dr/15.jpg",
          "/images/portfolio/134-700 Osgoode Dr/16.jpg",
          "/images/portfolio/134-700 Osgoode Dr/17.jpg",
          "/images/portfolio/134-700 Osgoode Dr/18.jpg",
          "/images/portfolio/134-700 Osgoode Dr/19.jpg",
          "/images/portfolio/134-700 Osgoode Dr/20.jpg",
          "/images/portfolio/134-700 Osgoode Dr/21.jpg",
          "/images/portfolio/134-700 Osgoode Dr/22.jpg",
          "/images/portfolio/134-700 Osgoode Dr/23.jpg",
          "/images/portfolio/134-700 Osgoode Dr/24.jpg",
          "/images/portfolio/134-700 Osgoode Dr/25.jpg",
          "/images/portfolio/134-700 Osgoode Dr/26.jpg",
          "/images/portfolio/134-700 Osgoode Dr/27.jpg",
          "/images/portfolio/134-700 Osgoode Dr/28.jpg",
          "/images/portfolio/134-700 Osgoode Dr/29.jpg",
          "/images/portfolio/134-700 Osgoode Dr/30.jpg",
        ],
      },
      {
        id: 14,
        serviceId: 10,
        title: "194 Rexleigh",
        images: [
          "/images/portfolio/194 Rexleigh/1.jpg",
          "/images/portfolio/194 Rexleigh/2.jpg",
          "/images/portfolio/194 Rexleigh/3.jpg",
          "/images/portfolio/194 Rexleigh/4.jpg",
          "/images/portfolio/194 Rexleigh/5.jpg",
          "/images/portfolio/194 Rexleigh/6.jpg",
          "/images/portfolio/194 Rexleigh/7.jpg",
          "/images/portfolio/194 Rexleigh/8.jpg",
          "/images/portfolio/194 Rexleigh/9.jpg",
          "/images/portfolio/194 Rexleigh/10.jpg",
          "/images/portfolio/194 Rexleigh/11.jpg",
          "/images/portfolio/194 Rexleigh/12.jpg",
          "/images/portfolio/194 Rexleigh/13.jpg",
          "/images/portfolio/194 Rexleigh/14.jpg",
          "/images/portfolio/194 Rexleigh/15.jpg",
          "/images/portfolio/194 Rexleigh/16.jpg",
          "/images/portfolio/194 Rexleigh/17.jpg",
          "/images/portfolio/194 Rexleigh/18.jpg",
        ],
      },
      {
        id: 15,
        serviceId: 10,
        title: "479 Carlton Balconies and Concrete",
        images: [
          "/images/portfolio/479 Carlton Balconies and Concrete/1.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/2.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/3.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/4.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/5.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/6.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/7.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/8.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/9.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/10.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/11.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/12.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/13.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/14.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/15.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/16.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/17.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/18.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/19.jpg",
        ],
      },
      {
        id: 16,
        serviceId: 10,
        title: "2404 Queensway Dr",
        images: [
          "/images/portfolio/2404 Queensway Dr/1.jpg",
          "/images/portfolio/2404 Queensway Dr/2.jpg",
          "/images/portfolio/2404 Queensway Dr/3.jpg",
          "/images/portfolio/2404 Queensway Dr/4.jpg",
          "/images/portfolio/2404 Queensway Dr/5.jpg",
          "/images/portfolio/2404 Queensway Dr/6.jpg",
          "/images/portfolio/2404 Queensway Dr/7.jpg",
          "/images/portfolio/2404 Queensway Dr/8.jpg",
          "/images/portfolio/2404 Queensway Dr/9.jpg",
          "/images/portfolio/2404 Queensway Dr/10.jpg",
          "/images/portfolio/2404 Queensway Dr/11.jpg",
          "/images/portfolio/2404 Queensway Dr/12.jpg",
          "/images/portfolio/2404 Queensway Dr/13.jpg",
          "/images/portfolio/2404 Queensway Dr/14.jpg",
          "/images/portfolio/2404 Queensway Dr/15.jpg",
          "/images/portfolio/2404 Queensway Dr/16.jpg",
          "/images/portfolio/2404 Queensway Dr/17.jpg",
          "/images/portfolio/2404 Queensway Dr/18.jpg",
          "/images/portfolio/2404 Queensway Dr/19.jpg",
          "/images/portfolio/2404 Queensway Dr/20.jpg",
        ],
      },
      {
        id: 17,
        serviceId: 10,
        title: "5017 Victoria Ave",
        images: [
          "/images/portfolio/5017 Victoria Ave/1.jpg",
          "/images/portfolio/5017 Victoria Ave/2.jpg",
          "/images/portfolio/5017 Victoria Ave/3.jpg",
          "/images/portfolio/5017 Victoria Ave/4.jpg",
          "/images/portfolio/5017 Victoria Ave/5.jpg",
          "/images/portfolio/5017 Victoria Ave/6.jpg",
          "/images/portfolio/5017 Victoria Ave/7.jpg",
          "/images/portfolio/5017 Victoria Ave/8.jpg",
          "/images/portfolio/5017 Victoria Ave/9.jpg",
          "/images/portfolio/5017 Victoria Ave/10.jpg",
          "/images/portfolio/5017 Victoria Ave/11.jpg",
          "/images/portfolio/5017 Victoria Ave/12.jpg",
          "/images/portfolio/5017 Victoria Ave/13.jpg",
          "/images/portfolio/5017 Victoria Ave/14.jpg",
        ],
      },
      {
        id: 18,
        serviceId: 10,
        title: "6858 and 6868 Ailanthus Ave",
        images: [
          "/images/portfolio/6858 and 6868 Ailanthus Ave/1.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/2.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/3.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/4.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/5.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/6.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/7.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/8.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/9.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/10.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/11.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/12.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/13.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/14.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/15.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/16.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/17.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/18.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/19.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/20.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/21.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/22.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/23.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/24.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/25.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/26.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/27.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/28.jpg",
        ],
      },
      {
        id: 19,
        serviceId: 10,
        title: "The Meadoways",
        images: [
          "/images/portfolio/The Meadoways/1.jpg",
          "/images/portfolio/The Meadoways/2.jpg",
          "/images/portfolio/The Meadoways/3.jpg",
          "/images/portfolio/The Meadoways/4.jpg",
          "/images/portfolio/The Meadoways/5.jpg",
          "/images/portfolio/The Meadoways/6.jpg",
          "/images/portfolio/The Meadoways/7.jpg",
          "/images/portfolio/The Meadoways/8.jpg",
          "/images/portfolio/The Meadoways/9.jpg",
          "/images/portfolio/The Meadoways/10.jpg",
          "/images/portfolio/The Meadoways/11.jpg",
          "/images/portfolio/The Meadoways/12.jpg",
          "/images/portfolio/The Meadoways/13.jpg",
          "/images/portfolio/The Meadoways/14.jpg",
          "/images/portfolio/The Meadoways/15.jpg",
          "/images/portfolio/The Meadoways/16.jpg",
          "/images/portfolio/The Meadoways/17.jpg",
          "/images/portfolio/The Meadoways/18.jpg",
          "/images/portfolio/The Meadoways/19.jpg",
          "/images/portfolio/The Meadoways/20.jpg",
          "/images/portfolio/The Meadoways/21.jpg",
          "/images/portfolio/The Meadoways/22.jpg",
          "/images/portfolio/The Meadoways/23.jpg",
          "/images/portfolio/The Meadoways/24.jpg",
          "/images/portfolio/The Meadoways/25.jpg",
          "/images/portfolio/The Meadoways/26.jpg",
          "/images/portfolio/The Meadoways/27.jpg",
          "/images/portfolio/The Meadoways/28.jpg",
        ],
      },
      {
        id: 20,
        serviceId: 10,
        title: "479 Carlton Windows and Doors",
        images: [
          "/images/portfolio/479 Carlton Windows and Doors/1.jpg",
          "/images/portfolio/479 Carlton Windows and Doors/2.jpg",
          "/images/portfolio/479 Carlton Windows and Doors/3.jpg",
          "/images/portfolio/479 Carlton Windows and Doors/4.jpg",
        ]
      },
      {
        id: 21,
        serviceId: 10,
        title: "Underground Garage Repairs- 1775",
        images: [
          "/images/portfolio/Underground Garage/1.jpg",
          "/images/portfolio/Underground Garage/2.jpg",
          "/images/portfolio/Underground Garage/3.jpg",
          "/images/portfolio/Underground Garage/4.jpg",
          "/images/portfolio/Underground Garage/5.jpg",
        ],
      },
      {
        id: 22,
        serviceId: 10,
        title: "Metal Cladding Project",
        images: [
          "/images/portfolio/Metal Cladding Project/1.jpg",
          "/images/portfolio/Metal Cladding Project/2.jpg",
          "/images/portfolio/Metal Cladding Project/3.jpg",
          "/images/portfolio/Metal Cladding Project/4.jpg",
          "/images/portfolio/Metal Cladding Project/5.jpg",
          "/images/portfolio/Metal Cladding Project/6.jpg",
        ],
      },
      {
        id: 23,
        serviceId: 10,
        title: "2875 Yonge St - Historic Restoration",
        images: [
            "/images/portfolio/2875 Yonge St - Historic Restoration/1.jpg",
            "/images/portfolio/2875 Yonge St - Historic Restoration/2.jpg",
            "/images/portfolio/2875 Yonge St - Historic Restoration/3.jpg",
            "/images/portfolio/2875 Yonge St - Historic Restoration/4.jpg",
            "/images/portfolio/2875 Yonge St - Historic Restoration/5.jpg",
            "/images/portfolio/2875 Yonge St - Historic Restoration/6.jpg",
        ]
      },
      {
        id: 24,
        serviceId: 10,
        title: "Cladding Replacement- 26 Holmesway Pl",
        images: [
            "/images/portfolio/Cladding Replacement- 1478 Elm Rd., Oakville/1.jpg",
            "/images/portfolio/Cladding Replacement- 1478 Elm Rd., Oakville/2.jpg",
            "/images/portfolio/Cladding Replacement- 1478 Elm Rd., Oakville/3.jpg",
            "/images/portfolio/Cladding Replacement- 1478 Elm Rd., Oakville/4.jpg",
            "/images/portfolio/Cladding Replacement- 1478 Elm Rd., Oakville/5.jpg",
        ]
      },
      {
        id: 25,
        serviceId: 10,
        title: "Balcony Renewal- 315 Colborne St. W., Whitby",
        images: [
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/1.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/2.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/3.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/4.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/5.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/6.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/7.png",
            "/images/portfolio/Balcony Renewal- 315 Colborne St. W., Whitby/8.png",
        ]
      },
      {
        id: 26,
        serviceId: 10,
        title: "1319 Neilson Rd., Scarborough",
        images: [
            "/images/portfolio/1319 Neilson Rd., Scarborough/1.jpg",
            "/images/portfolio/1319 Neilson Rd., Scarborough/2.jpg",
            "/images/portfolio/1319 Neilson Rd., Scarborough/3.jpg",
            "/images/portfolio/1319 Neilson Rd., Scarborough/4.jpg",
            "/images/portfolio/1319 Neilson Rd., Scarborough/5.jpg",
            "/images/portfolio/1319 Neilson Rd., Scarborough/6.jpg",
            "/images/portfolio/1319 Neilson Rd., Scarborough/7.jpg",
        ]
      },
      {
        id: 27,
        serviceId: 10,
        title: "234 Munro St., Toronto",
        images: [
            "/images/portfolio/234 Munro St., Toronto/1.jpg",
            "/images/portfolio/234 Munro St., Toronto/2.jpg",
            "/images/portfolio/234 Munro St., Toronto/3.jpg",
            "/images/portfolio/234 Munro St., Toronto/4.jpg",
            "/images/portfolio/234 Munro St., Toronto/5.jpg",
            "/images/portfolio/234 Munro St., Toronto/6.jpg",
            "/images/portfolio/234 Munro St., Toronto/7.jpg",
        ]
      },
      {
        id: 28,
        serviceId: 10,
        title: "Foundation Waterproofing- 220 Kinzie Ave.",
        images: [
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./1.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./2.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./3.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./4.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./5.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./6.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./7.jpg",
            "/images/portfolio/Foundation Waterproofing- 220 Kinzie Ave./8.jpg",
        ]
      },
      {
        id: 29,
        serviceId: 10,
        title: "Foundation Waterproofing- Bank of Montreal",
        images: [
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/1.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/2.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/3.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/4.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/5.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/6.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/7.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/8.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/9.png",
            "/images/portfolio/Foundation Waterproofing- Bank of Montreal/10.png",
        ]
      },
      {
        id: 30,
        serviceId: 10,
        title: "Garbage Room Upgrade- 111 Chestnut St.",
        images: [
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./1.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./2.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./3.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./4.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./5.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./6.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./7.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./8.jpg",
            "/images/portfolio/Garbage Room Upgrade- 111 Chestnut St./9.jpg",
        ]
      },
      {
        id: 31,
        serviceId: 10,
        title: "Central Public School, Brampton",
        images: [
            "/images/portfolio/Central Public School, Brampton/1.jpg",
            "/images/portfolio/Central Public School, Brampton/2.jpg",
            "/images/portfolio/Central Public School, Brampton/3.jpg",
            "/images/portfolio/Central Public School, Brampton/4.jpg",
            "/images/portfolio/Central Public School, Brampton/5.jpg",
            "/images/portfolio/Central Public School, Brampton/6.jpg",
        ]
      },
      {
        id: 32,
        serviceId: 10,
        title: "Hydro Vault Units- Door Replacement, Electric, Structural",
        images: [
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/1.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/2.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/3.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/4.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/5.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/6.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/7.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/8.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/9.jpg",
            "/images/portfolio/Hydro Vault Units- Door Replacement, Electric, Structural/10.jpg",
        ]
      },
      {
        id: 33,
        serviceId: 10,
        title: "Brampton Fire Station",
        images: [
            "/images/portfolio/Brampton Fire Station/1.jpg",
            "/images/portfolio/Brampton Fire Station/2.jpg",
            "/images/portfolio/Brampton Fire Station/3.jpg",
            "/images/portfolio/Brampton Fire Station/4.png",
            "/images/portfolio/Brampton Fire Station/5.png",
            "/images/portfolio/Brampton Fire Station/6.png",
            "/images/portfolio/Brampton Fire Station/7.png",
            "/images/portfolio/Brampton Fire Station/8.png",
        ]
      },
      {
        id: 34,
        serviceId: 10,
        title: "743-751 Steeles Ave. W., North York",
        images: [
            "/images/portfolio/743-751 Steeles Ave. W., North York/1.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/2.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/3.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/4.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/5.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/6.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/7.jpg",
            "/images/portfolio/743-751 Steeles Ave. W., North York/8.jpg",
        ]
      },
      {
        id: 35,
        serviceId: 10,
        title: "Fairview Public School",
        images: [
            "/images/portfolio/Fairview Public School/1.jpg",
            "/images/portfolio/Fairview Public School/2.jpg",
            "/images/portfolio/Fairview Public School/3.jpg",
            "/images/portfolio/Fairview Public School/4.jpg",
            "/images/portfolio/Fairview Public School/5.jpg",
            "/images/portfolio/Fairview Public School/6.jpg",
            "/images/portfolio/Fairview Public School/7.jpg",
        ]
      }
    ],
  }),
  getters: {
    get: (state) => state.projects,
    getById: (state) => {
      return (id: number) => state.projects.find((proj) => proj.id === id);
    },
  },
});
