import { defineStore } from "pinia";

export interface Project {
  id: number;
  service_id: number;
  title: string;
  images: string[];
  address?: string;
}

export const useProjectsStore = defineStore("projects", {
  state: () => ({
    projects: <Project[]>[
      {
        id: 1,
        service_id: 1,
        title: "Building Restoration Project",
        images: [
          "/images/projects/building_restoration/1.jpg",
          "/images/projects/building_restoration/2.jpg",
          "/images/projects/building_restoration/3.jpg",
          "/images/projects/building_restoration/4.jpg",
          "/images/projects/building_restoration/5.jpg",
          "/images/projects/building_restoration/6.jpg",
          "/images/projects/building_restoration/7.jpg",
          "/images/projects/building_restoration/8.jpg",
        ],
      },
      {
        id: 2,
        service_id: 2,
        title: "Concrete Work Project",
        images: [
          "/images/projects/concreate_work/1.jpg",
          "/images/projects/concreate_work/2.jpg",
          "/images/projects/concreate_work/3.jpg",
          "/images/projects/concreate_work/4.jpg",
          "/images/projects/concreate_work/5.jpg",
          "/images/projects/concreate_work/6.jpg",
          "/images/projects/concreate_work/7.jpg",
          "/images/projects/concreate_work/8.jpg",
        ],
      },
      {
        id: 3,
        service_id: 3,
        title: "Foundation Services Project",
        images: [
          "/images/projects/foundation_services/1.jpg",
          "/images/projects/foundation_services/2.jpg",
          "/images/projects/foundation_services/3.jpg",
          "/images/projects/foundation_services/4.jpg",
          "/images/projects/foundation_services/5.jpg",
          "/images/projects/foundation_services/6.jpg",
          "/images/projects/foundation_services/7.jpg",
          "/images/projects/foundation_services/8.jpg",
        ],
      },
      {
        id: 4,
        service_id: 4,
        title: "Exterior Finishing Project",
        images: [
          "/images/projects/exterior_finishing/1.jpg",
          "/images/projects/exterior_finishing/2.jpg",
          "/images/projects/exterior_finishing/3.jpg",
          "/images/projects/exterior_finishing/4.jpg",
          "/images/projects/exterior_finishing/5.jpg",
          "/images/projects/exterior_finishing/6.jpg",
          "/images/projects/exterior_finishing/7.jpg",
          "/images/projects/exterior_finishing/8.jpg",
          "/images/projects/exterior_finishing/9.jpg",
        ],
      },
      {
        id: 5,
        service_id: 5,
        title: "Windows & Doors Project",

        images: [
          "/images/projects/windows_doors/1.jpg",
          "/images/projects/windows_doors/2.jpg",
          "/images/projects/windows_doors/3.jpeg",
          "/images/projects/windows_doors/4.jpeg",
          "/images/projects/windows_doors/5.jpeg",
          "/images/projects/windows_doors/6.jpeg",
          "/images/projects/windows_doors/7.jpeg",
          "/images/projects/windows_doors/8.jpeg",
        ],
      },
      {
        id: 6,
        service_id: 6,
        title: "Roofing Services Project",
        images: [
          "/images/projects/roofing-services/1.jpg",
          "/images/projects/roofing-services/2.jpg",
          "/images/projects/roofing-services/3.jpg",
          "/images/projects/roofing-services/4.jpg",
          "/images/projects/roofing-services/5.jpg",
          "/images/projects/roofing-services/6.jpg",
          "/images/projects/roofing-services/7.jpg",
          "/images/projects/roofing-services/8.jpg",
        ],
      },
      {
        id: 7,
        service_id: 7,
        title: "Waterproofing Project",
        images: [
          "/images/projects/waterproofing/1.jpg",
          "/images/projects/waterproofing/2.jpg",
          "/images/projects/waterproofing/3.jpg",
          "/images/projects/waterproofing/4.jpg",
          "/images/projects/waterproofing/5.jpg",
          "/images/projects/waterproofing/6.jpg",
          "/images/projects/waterproofing/7.jpg",
          "/images/projects/waterproofing/8.jpg",
        ],
      },
      {
        id: 8,
        service_id: 8,
        title: "Demolition & Excavation Project",
        images: [
          "/images/projects/demolition_excavation/1.jpg",
          "/images/projects/demolition_excavation/2.jpg",
          "/images/projects/demolition_excavation/3.jpg",
          "/images/projects/demolition_excavation/4.jpg",
          "/images/projects/demolition_excavation/5.jpg",
          "/images/projects/demolition_excavation/6.jpg",
          "/images/projects/demolition_excavation/7.jpg",
          "/images/projects/demolition_excavation/8.jpg",
          "/images/projects/demolition_excavation/9.jpg",
        ],
      },
      {
        id: 9,
        service_id: 9,
        title: "Tashkent",
        images: [
          "/images/projects/tashkent/1.jpg",
          "/images/projects/tashkent/2.jpg",
          "/images/projects/tashkent/3.jpg",
          "/images/projects/tashkent/4.jpg",
          "/images/projects/tashkent/5.jpg",
          "/images/projects/tashkent/6.jpg",
          "/images/projects/tashkent/7.jpg",
        ],
        address: "Tashkent Region, Tashkent City, Sergeli District, House",
      },
      {
        id: 10,
        service_id: 9,
        title: "Bukhara",
        images: [
          "/images/projects/bukhara/1.jpg",
          "/images/projects/bukhara/2.jpg",
          "/images/projects/bukhara/3.jpg",
          "/images/projects/bukhara/4.jpg",
          "/images/projects/bukhara/5.jpg",
          "/images/projects/bukhara/6.jpg",
          "/images/projects/bukhara/7.jpg",
          "/images/projects/bukhara/8.jpg",
        ],
        address:
          "Bukhara Region, Bukhara City, Abu Ali Ibn Sina Street, House 46/1",
      },
      {
        id: 11,
        service_id: 9,
        title: "Tashkent",
        images: [
          "/images/projects/tashkent-2/1.jpg",
          "/images/projects/tashkent-2/2.jpg",
          "/images/projects/tashkent-2/3.jpg",
          "/images/projects/tashkent-2/4.jpg",
          "/images/projects/tashkent-2/5.jpg",
          "/images/projects/tashkent-2/6.jpg",
          "/images/projects/tashkent-2/7.jpg",
        ],
        address:
          "Tashkent Region, Tashkent City, Yangi Hayot District, Yangi Darxon Mahalla, Navruz Street, Houses 61, 62, 63",
      },
      {
        id: 12,
        serviceId: 10,
        title: "10-26 Holmesway Pl, Acton",
        images: [
          "/images/portfolio/10-26 Holmesway Pl, Acton/1.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/2.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/3.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/4.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/5.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/6.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/7.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/8.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/9.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/10.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/11.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/12.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/13.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/14.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/15.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/16.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/17.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/18.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/19.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/20.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/21.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/22.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/23.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/24.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/25.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/26.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/27.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/28.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/29.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/30.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/31.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/32.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/33.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/34.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/35.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/36.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/37.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/38.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/39.jpg",
          "/images/portfolio/10-26 Holmesway Pl, Acton/40.jpg",
        ],
      },
      {
        id: 12,
        serviceId: 10,
        title: "134-700 Osgoode Dr",
        images: [
          "/images/portfolio/134-700 Osgoode Dr/1.jpg",
          "/images/portfolio/134-700 Osgoode Dr/2.jpg",
          "/images/portfolio/134-700 Osgoode Dr/3.jpg",
          "/images/portfolio/134-700 Osgoode Dr/4.jpg",
          "/images/portfolio/134-700 Osgoode Dr/5.jpg",
          "/images/portfolio/134-700 Osgoode Dr/6.jpg",
          "/images/portfolio/134-700 Osgoode Dr/7.jpg",
          "/images/portfolio/134-700 Osgoode Dr/8.jpg",
          "/images/portfolio/134-700 Osgoode Dr/9.jpg",
          "/images/portfolio/134-700 Osgoode Dr/10.jpg",
          "/images/portfolio/134-700 Osgoode Dr/11.jpg",
          "/images/portfolio/134-700 Osgoode Dr/12.jpg",
          "/images/portfolio/134-700 Osgoode Dr/13.jpg",
          "/images/portfolio/134-700 Osgoode Dr/14.jpg",
          "/images/portfolio/134-700 Osgoode Dr/15.jpg",
          "/images/portfolio/134-700 Osgoode Dr/16.jpg",
          "/images/portfolio/134-700 Osgoode Dr/17.jpg",
          "/images/portfolio/134-700 Osgoode Dr/18.jpg",
          "/images/portfolio/134-700 Osgoode Dr/19.jpg",
          "/images/portfolio/134-700 Osgoode Dr/20.jpg",
          "/images/portfolio/134-700 Osgoode Dr/21.jpg",
          "/images/portfolio/134-700 Osgoode Dr/22.jpg",
          "/images/portfolio/134-700 Osgoode Dr/23.jpg",
          "/images/portfolio/134-700 Osgoode Dr/24.jpg",
          "/images/portfolio/134-700 Osgoode Dr/25.jpg",
          "/images/portfolio/134-700 Osgoode Dr/26.jpg",
          "/images/portfolio/134-700 Osgoode Dr/27.jpg",
          "/images/portfolio/134-700 Osgoode Dr/28.jpg",
          "/images/portfolio/134-700 Osgoode Dr/29.jpg",
          "/images/portfolio/134-700 Osgoode Dr/30.jpg",
        ],
      },
      {
        id: 14,
        serviceId: 10,
        title: "194 Rexleigh",
        images: [
          "/images/portfolio/194 Rexleigh/1.jpg",
          "/images/portfolio/194 Rexleigh/2.jpg",
          "/images/portfolio/194 Rexleigh/3.jpg",
          "/images/portfolio/194 Rexleigh/4.jpg",
          "/images/portfolio/194 Rexleigh/5.jpg",
          "/images/portfolio/194 Rexleigh/6.jpg",
          "/images/portfolio/194 Rexleigh/7.jpg",
          "/images/portfolio/194 Rexleigh/8.jpg",
          "/images/portfolio/194 Rexleigh/9.jpg",
          "/images/portfolio/194 Rexleigh/10.jpg",
          "/images/portfolio/194 Rexleigh/11.jpg",
          "/images/portfolio/194 Rexleigh/12.jpg",
          "/images/portfolio/194 Rexleigh/13.jpg",
          "/images/portfolio/194 Rexleigh/14.jpg",
          "/images/portfolio/194 Rexleigh/15.jpg",
          "/images/portfolio/194 Rexleigh/16.jpg",
          "/images/portfolio/194 Rexleigh/17.jpg",
          "/images/portfolio/194 Rexleigh/18.jpg",
        ],
      },
      {
        id: 15,
        serviceId: 10,
        title: "479 Carlton Balconies and Concrete",
        images: [
          "/images/portfolio/479 Carlton Balconies and Concrete/1.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/2.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/3.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/4.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/5.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/6.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/7.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/8.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/9.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/10.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/11.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/12.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/13.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/14.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/15.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/16.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/17.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/18.jpg",
          "/images/portfolio/479 Carlton Balconies and Concrete/19.jpg",
        ],
      },
      {
        id: 16,
        serviceId: 10,
        title: "2404 Queensway Dr",
        images: [
          "/images/portfolio/2404 Queensway Dr/1.jpg",
          "/images/portfolio/2404 Queensway Dr/2.jpg",
          "/images/portfolio/2404 Queensway Dr/3.jpg",
          "/images/portfolio/2404 Queensway Dr/4.jpg",
          "/images/portfolio/2404 Queensway Dr/5.jpg",
          "/images/portfolio/2404 Queensway Dr/6.jpg",
          "/images/portfolio/2404 Queensway Dr/7.jpg",
          "/images/portfolio/2404 Queensway Dr/8.jpg",
          "/images/portfolio/2404 Queensway Dr/9.jpg",
          "/images/portfolio/2404 Queensway Dr/10.jpg",
          "/images/portfolio/2404 Queensway Dr/11.jpg",
          "/images/portfolio/2404 Queensway Dr/12.jpg",
          "/images/portfolio/2404 Queensway Dr/13.jpg",
          "/images/portfolio/2404 Queensway Dr/14.jpg",
          "/images/portfolio/2404 Queensway Dr/15.jpg",
          "/images/portfolio/2404 Queensway Dr/16.jpg",
          "/images/portfolio/2404 Queensway Dr/17.jpg",
          "/images/portfolio/2404 Queensway Dr/18.jpg",
          "/images/portfolio/2404 Queensway Dr/19.jpg",
          "/images/portfolio/2404 Queensway Dr/20.jpg",
        ],
      },
      {
        id: 17,
        serviceId: 10,
        title: "5017 Victoria Ave",
        images: [
          "/images/portfolio/5017 Victoria Ave/1.jpg",
          "/images/portfolio/5017 Victoria Ave/2.jpg",
          "/images/portfolio/5017 Victoria Ave/3.jpg",
          "/images/portfolio/5017 Victoria Ave/4.jpg",
          "/images/portfolio/5017 Victoria Ave/5.jpg",
          "/images/portfolio/5017 Victoria Ave/6.jpg",
          "/images/portfolio/5017 Victoria Ave/7.jpg",
          "/images/portfolio/5017 Victoria Ave/8.jpg",
          "/images/portfolio/5017 Victoria Ave/9.jpg",
          "/images/portfolio/5017 Victoria Ave/10.jpg",
          "/images/portfolio/5017 Victoria Ave/11.jpg",
          "/images/portfolio/5017 Victoria Ave/12.jpg",
          "/images/portfolio/5017 Victoria Ave/13.jpg",
          "/images/portfolio/5017 Victoria Ave/14.jpg",
        ],
      },
      {
        id: 18,
        serviceId: 10,
        title: "6858 and 6868 Ailanthus Ave",
        images: [
          "/images/portfolio/6858 and 6868 Ailanthus Ave/1.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/2.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/3.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/4.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/5.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/6.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/7.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/8.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/9.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/10.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/11.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/12.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/13.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/14.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/15.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/16.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/17.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/18.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/19.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/20.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/21.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/22.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/23.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/24.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/25.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/26.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/27.jpg",
          "/images/portfolio/6858 and 6868 Ailanthus Ave/28.jpg",
        ],
      },
      {
        id: 19,
        serviceId: 10,
        title: "The Meadoways",
        images: [
          "/images/portfolio/The Meadoways/1.jpg",
          "/images/portfolio/The Meadoways/2.jpg",
          "/images/portfolio/The Meadoways/3.jpg",
          "/images/portfolio/The Meadoways/4.jpg",
          "/images/portfolio/The Meadoways/5.jpg",
          "/images/portfolio/The Meadoways/6.jpg",
          "/images/portfolio/The Meadoways/7.jpg",
          "/images/portfolio/The Meadoways/8.jpg",
          "/images/portfolio/The Meadoways/9.jpg",
          "/images/portfolio/The Meadoways/10.jpg",
          "/images/portfolio/The Meadoways/11.jpg",
          "/images/portfolio/The Meadoways/12.jpg",
          "/images/portfolio/The Meadoways/13.jpg",
          "/images/portfolio/The Meadoways/14.jpg",
          "/images/portfolio/The Meadoways/15.jpg",
          "/images/portfolio/The Meadoways/16.jpg",
          "/images/portfolio/The Meadoways/17.jpg",
          "/images/portfolio/The Meadoways/18.jpg",
          "/images/portfolio/The Meadoways/19.jpg",
          "/images/portfolio/The Meadoways/20.jpg",
          "/images/portfolio/The Meadoways/21.jpg",
          "/images/portfolio/The Meadoways/22.jpg",
          "/images/portfolio/The Meadoways/23.jpg",
          "/images/portfolio/The Meadoways/24.jpg",
          "/images/portfolio/The Meadoways/25.jpg",
          "/images/portfolio/The Meadoways/26.jpg",
          "/images/portfolio/The Meadoways/27.jpg",
          "/images/portfolio/The Meadoways/28.jpg",
        ],
      },
    ],
  }),
  getters: {
    get: (state) => state.projects,
    getByServiceId: (state) => {
      return (service_id: number) =>
        state.projects.filter((project) => project.service_id === service_id);
    },
    getById: (state) => {
      return (id: number) => state.projects.find((project) => project.id === id);
    }
  },
});
